FROM ubuntu:latest

LABEL org.opencontainers.image.source=https://github.com/Walchand-Linux-Users-Group/linux-diary

RUN apt-get update

RUN mkdir /home/wlug

WORKDIR /home/wlug

RUN echo "mndnnwejnjesrehtomorf plehemostegnacew ebyamsneppahtahw txetsirewejyrtstel">answer00

RUN echo "amdsmzmmdjiejmekn sniondplehnacesle emosebyamtxet sirewejemosmaineveyeh">answer01

RUN echo "flahdnocesebnac erehwflahtsujstitub }_709107728{GULW siyekfotraptsrifehtyllanifemtoguoy">answer02

RUN echo "rewsnarofmeht kcehcplehnacyeht ebyamsrehtoksa txetsirewejemosmai">answer03

RUN chmod 444 answer00

RUN chmod 444 answer01

RUN chmod 444 answer02

RUN chmod 444 answer03

RUN gzip answer00

RUN gzip answer01

RUN gzip answer02

RUN gzip answer03

RUN mkdir /home/linuxDiary3

WORKDIR /home/linuxDiary3

RUN echo "jeweristextorsomeusefulinformation\njeweristextorsomeusefulinformation\njeweristextorsomeusefulinformation\njeweristextorsomeusefulinformation\nLet's See Your Knowledge The Second Half will be a number equal to number of unique lines in the file !!!\nLet's See Your Knowledge The Second Half will be a number equal to number of unique lines in the file !!! \nLet's See Your Knowledge The Second Half will be a number equal to number of unique lines in the file !!! \nLet's See Your Knowledge The Second Half will be a number equal to number of unique lines in the file !!! \nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing">.itmaybehere02

RUN echo "jeweristextorsomeusefulinformation\njeweristextorsomeusefulinformation\njeweristextorsomeusefulinformation\njeweristextorsomeusefulinformation\nwowyoucanlookforotherfilesnow\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing">.itmaybehere01

RUN echo "jeweristextorsomeusefulinformation\njeweristextorsomeusefulinformation\nksdsioasnasddjnijdjidsnsds\njbahjbhusajjsauiwuwiaw\njeweristextorsomeusefulinformation\jeweristextorsomeusefulinformation\nwowyoucanlookforotherfilesnow\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing\nAgainSOmeJewerisTextisComing">.itmaybehere00

RUN chmod 444 .itmaybehere00

RUN chmod 444 .itmaybehere01

RUN chmod 444 .itmaybehere02

WORKDIR /home

RUN echo "1) Last Task is waiting for you !!!\n\n\n2) Possible Commands for the task -> cd, ls, wc, uniq, gunzip, tac\n\nAll The Best !!!">README

RUN chmod 444 README

CMD ["/bin/bash"]